# Generated by Django 5.1.5 on 2025-05-27 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Chat nomi.", max_length=255, null=True
                    ),
                ),
                (
                    "message_count",
                    models.PositiveBigIntegerField(
                        default=0, help_text="O'qilmagan xabarlar soni."
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="chats", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Room",
                "verbose_name_plural": "Chat Rooms",
                "db_table": "chat_rooms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.TextField(blank=True, help_text="Xabar matni.", null=True),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Xabar fayli.",
                        null=True,
                        upload_to="chat_files/",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Xabar o'qilganligini bildiradi."
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        help_text="Xabar tegishli bo'lgan chat xonasi.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="websocket.chatroom",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="Xabarni yuborgan foydalanuvchi.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="chatroom",
            name="last_message",
            field=models.ForeignKey(
                blank=True,
                help_text="Chatdagi oxirgi xabar.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_message",
                to="websocket.message",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.TextField(verbose_name="Xabar")),
                ("message_uz", models.TextField(null=True, verbose_name="Xabar")),
                ("message_ru", models.TextField(null=True, verbose_name="Xabar")),
                ("message_en", models.TextField(null=True, verbose_name="Xabar")),
                ("message_ko", models.TextField(null=True, verbose_name="Xabar")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="O'qilgan"),
                ),
                (
                    "is_sending",
                    models.BooleanField(default=False, verbose_name="Jo'natilmoqda"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirishnoma",
                "verbose_name_plural": "Bildirishnomalar",
                "db_table": "notification",
            },
        ),
    ]
