# Generated by Django 5.1.5 on 2025-06-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websocket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="notifications/images/",
                verbose_name="Rasm",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Sarlavha"
            ),
        ),
    ]
