# Generated by Django 5.1.5 on 2025-06-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("websocket", "0002_notification_image_notification_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Bildirishnoma",
                "verbose_name_plural": "Bildirishnomalar",
            },
        ),
    ]
