# Generated by Django 5.1.5 on 2025-06-16 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pedagog", "0011_degree_name_en_degree_name_ko_degree_name_ru_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeratorPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="moderator_permissions",
                        to="pedagog.classes",
                        verbose_name="Sinf",
                    ),
                ),
                (
                    "school_type",
                    models.ManyToManyField(
                        blank=True,
                        related_name="moderator_permissions",
                        to="pedagog.schooltype",
                        verbose_name="Maktab turi",
                    ),
                ),
                (
                    "science",
                    models.ManyToManyField(
                        blank=True,
                        related_name="moderator_permissions",
                        to="pedagog.science",
                        verbose_name="Fan",
                    ),
                ),
                (
                    "science_language",
                    models.ManyToManyField(
                        blank=True,
                        related_name="moderator_permissions",
                        to="pedagog.sciencelanguage",
                        verbose_name="Fan tili",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderator_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderator Permission",
                "verbose_name_plural": "Moderator Permissions",
                "unique_together": {("user", "status")},
            },
        ),
    ]
