# Generated by Django 5.1.5 on 2025-06-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moderator", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="moderatorpermission",
            unique_together=set(),
        ),
    ]
