# Generated by Django 5.1.5 on 2025-05-27 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "name_uz",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_ko",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Blog Category",
                "verbose_name_plural": "Blog Categories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="last name"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="phone")),
                ("text", models.TextField(verbose_name="text")),
            ],
            options={
                "verbose_name": "contact us",
                "verbose_name_plural": "contact us",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.TextField(verbose_name="Savol")),
                ("question_uz", models.TextField(null=True, verbose_name="Savol")),
                ("question_ru", models.TextField(null=True, verbose_name="Savol")),
                ("question_en", models.TextField(null=True, verbose_name="Savol")),
                ("question_ko", models.TextField(null=True, verbose_name="Savol")),
                ("answer", models.TextField(verbose_name="Javob")),
                ("answer_uz", models.TextField(null=True, verbose_name="Javob")),
                ("answer_ru", models.TextField(null=True, verbose_name="Javob")),
                ("answer_en", models.TextField(null=True, verbose_name="Javob")),
                ("answer_ko", models.TextField(null=True, verbose_name="Javob")),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Category Name"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Category Name",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Category Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Category Name",
                    ),
                ),
                (
                    "name_ko",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Category Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "News Category",
                "verbose_name_plural": "News Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PedagogInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the pedagog info",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        help_text="Title of the pedagog info",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        help_text="Title of the pedagog info",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        help_text="Title of the pedagog info",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_ko",
                    models.CharField(
                        help_text="Title of the pedagog info",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the pedagog info",
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_uz",
                    models.TextField(
                        help_text="Description of the pedagog info",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        help_text="Description of the pedagog info",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        help_text="Description of the pedagog info",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_ko",
                    models.TextField(
                        help_text="Description of the pedagog info",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image of the pedagog info",
                        upload_to="pedagog/info/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Icon of the pedagog info",
                        max_length=255,
                        verbose_name="Icon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedagog Info",
                "verbose_name_plural": "Pedagog Info",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrivacyPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the privacy policy.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        help_text="Title of the privacy policy.",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        help_text="Title of the privacy policy.",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        help_text="Title of the privacy policy.",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_ko",
                    models.CharField(
                        help_text="Title of the privacy policy.",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Content of the privacy policy.",
                        verbose_name="Content",
                    ),
                ),
                (
                    "content_uz",
                    models.TextField(
                        help_text="Content of the privacy policy.",
                        null=True,
                        verbose_name="Content",
                    ),
                ),
                (
                    "content_ru",
                    models.TextField(
                        help_text="Content of the privacy policy.",
                        null=True,
                        verbose_name="Content",
                    ),
                ),
                (
                    "content_en",
                    models.TextField(
                        help_text="Content of the privacy policy.",
                        null=True,
                        verbose_name="Content",
                    ),
                ),
                (
                    "content_ko",
                    models.TextField(
                        help_text="Content of the privacy policy.",
                        null=True,
                        verbose_name="Content",
                    ),
                ),
            ],
            options={
                "verbose_name": "Privacy Policy",
                "verbose_name_plural": "Privacy Policies",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Seo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seo_type",
                    models.CharField(
                        choices=[
                            ("HOMEPAGE", "Homepage"),
                            ("RESOURCE", "Resource"),
                            ("NEWS", "News"),
                            ("BLOG", "Blog"),
                            ("PRICE", "Price"),
                            ("CONTACT", "Contact"),
                            ("POPULAR_NEWS", "Popular News"),
                            ("TRENDING_NEWS", "Trending News"),
                        ],
                        db_index=True,
                        default="HOMEPAGE",
                        help_text="The type of the page for SEO.",
                        max_length=20,
                        verbose_name="SEO Type",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="The image for the page for SEO.",
                        null=True,
                        upload_to="seo/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        help_text="The title of the page for SEO.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        db_index=True,
                        help_text="The title of the page for SEO.",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True,
                        help_text="The title of the page for SEO.",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_index=True,
                        help_text="The title of the page for SEO.",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_ko",
                    models.CharField(
                        db_index=True,
                        help_text="The title of the page for SEO.",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        db_index=True,
                        help_text="The description of the page for SEO.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_uz",
                    models.TextField(
                        db_index=True,
                        help_text="The description of the page for SEO.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        db_index=True,
                        help_text="The description of the page for SEO.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        db_index=True,
                        help_text="The description of the page for SEO.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_ko",
                    models.TextField(
                        db_index=True,
                        help_text="The description of the page for SEO.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        db_index=True,
                        help_text="The keywords for the page for SEO.",
                        max_length=255,
                        verbose_name="Keywords",
                    ),
                ),
                (
                    "keywords_uz",
                    models.CharField(
                        db_index=True,
                        help_text="The keywords for the page for SEO.",
                        max_length=255,
                        null=True,
                        verbose_name="Keywords",
                    ),
                ),
                (
                    "keywords_ru",
                    models.CharField(
                        db_index=True,
                        help_text="The keywords for the page for SEO.",
                        max_length=255,
                        null=True,
                        verbose_name="Keywords",
                    ),
                ),
                (
                    "keywords_en",
                    models.CharField(
                        db_index=True,
                        help_text="The keywords for the page for SEO.",
                        max_length=255,
                        null=True,
                        verbose_name="Keywords",
                    ),
                ),
                (
                    "keywords_ko",
                    models.CharField(
                        db_index=True,
                        help_text="The keywords for the page for SEO.",
                        max_length=255,
                        null=True,
                        verbose_name="Keywords",
                    ),
                ),
                (
                    "opengraph_title",
                    models.CharField(
                        db_index=True,
                        help_text="The OpenGraph title of the page for SEO.",
                        max_length=255,
                        verbose_name="OpenGraph Title",
                    ),
                ),
                (
                    "opengraph_title_uz",
                    models.CharField(
                        db_index=True,
                        help_text="The OpenGraph title of the page for SEO.",
                        max_length=255,
                        null=True,
                        verbose_name="OpenGraph Title",
                    ),
                ),
                (
                    "opengraph_title_ru",
                    models.CharField(
                        db_index=True,
                        help_text="The OpenGraph title of the page for SEO.",
                        max_length=255,
                        null=True,
                        verbose_name="OpenGraph Title",
                    ),
                ),
                (
                    "opengraph_title_en",
                    models.CharField(
                        db_index=True,
                        help_text="The OpenGraph title of the page for SEO.",
                        max_length=255,
                        null=True,
                        verbose_name="OpenGraph Title",
                    ),
                ),
                (
                    "opengraph_title_ko",
                    models.CharField(
                        db_index=True,
                        help_text="The OpenGraph title of the page for SEO.",
                        max_length=255,
                        null=True,
                        verbose_name="OpenGraph Title",
                    ),
                ),
                (
                    "opengraph_description",
                    models.TextField(
                        db_index=True,
                        help_text="The OpenGraph description of the page for SEO.",
                        verbose_name="OpenGraph Description",
                    ),
                ),
                (
                    "opengraph_description_uz",
                    models.TextField(
                        db_index=True,
                        help_text="The OpenGraph description of the page for SEO.",
                        null=True,
                        verbose_name="OpenGraph Description",
                    ),
                ),
                (
                    "opengraph_description_ru",
                    models.TextField(
                        db_index=True,
                        help_text="The OpenGraph description of the page for SEO.",
                        null=True,
                        verbose_name="OpenGraph Description",
                    ),
                ),
                (
                    "opengraph_description_en",
                    models.TextField(
                        db_index=True,
                        help_text="The OpenGraph description of the page for SEO.",
                        null=True,
                        verbose_name="OpenGraph Description",
                    ),
                ),
                (
                    "opengraph_description_ko",
                    models.TextField(
                        db_index=True,
                        help_text="The OpenGraph description of the page for SEO.",
                        null=True,
                        verbose_name="OpenGraph Description",
                    ),
                ),
                (
                    "twitter_title",
                    models.CharField(
                        db_index=True,
                        help_text="The Twitter title of the page for SEO.",
                        max_length=255,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_title_uz",
                    models.CharField(
                        db_index=True,
                        help_text="The Twitter title of the page for SEO.",
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_title_ru",
                    models.CharField(
                        db_index=True,
                        help_text="The Twitter title of the page for SEO.",
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_title_en",
                    models.CharField(
                        db_index=True,
                        help_text="The Twitter title of the page for SEO.",
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_title_ko",
                    models.CharField(
                        db_index=True,
                        help_text="The Twitter title of the page for SEO.",
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_description",
                    models.TextField(
                        db_index=True,
                        help_text="The Twitter description of the page for SEO.",
                        verbose_name="Twitter Description",
                    ),
                ),
                (
                    "twitter_description_uz",
                    models.TextField(
                        db_index=True,
                        help_text="The Twitter description of the page for SEO.",
                        null=True,
                        verbose_name="Twitter Description",
                    ),
                ),
                (
                    "twitter_description_ru",
                    models.TextField(
                        db_index=True,
                        help_text="The Twitter description of the page for SEO.",
                        null=True,
                        verbose_name="Twitter Description",
                    ),
                ),
                (
                    "twitter_description_en",
                    models.TextField(
                        db_index=True,
                        help_text="The Twitter description of the page for SEO.",
                        null=True,
                        verbose_name="Twitter Description",
                    ),
                ),
                (
                    "twitter_description_ko",
                    models.TextField(
                        db_index=True,
                        help_text="The Twitter description of the page for SEO.",
                        null=True,
                        verbose_name="Twitter Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO",
                "verbose_name_plural": "SEOs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "title_uz",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "title_ko",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "short_title",
                    models.CharField(max_length=255, verbose_name="Short Title"),
                ),
                (
                    "short_title_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Short Title"
                    ),
                ),
                (
                    "short_title_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Short Title"
                    ),
                ),
                (
                    "short_title_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Short Title"
                    ),
                ),
                (
                    "short_title_ko",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Short Title"
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                ("content_uz", models.TextField(null=True, verbose_name="Content")),
                ("content_ru", models.TextField(null=True, verbose_name="Content")),
                ("content_en", models.TextField(null=True, verbose_name="Content")),
                ("content_ko", models.TextField(null=True, verbose_name="Content")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blogs/", verbose_name="Image"
                    ),
                ),
                (
                    "reading_time",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Reading Time",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogs",
                        to="home.blogcategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reading_time",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Estimated reading time for the article.",
                        max_length=255,
                        null=True,
                        verbose_name="Reading Time",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_ko",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "short_title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Short Title"
                    ),
                ),
                (
                    "short_title_uz",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Short Title",
                    ),
                ),
                (
                    "short_title_ru",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Short Title",
                    ),
                ),
                (
                    "short_title_en",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Short Title",
                    ),
                ),
                (
                    "short_title_ko",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Short Title",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, db_index=True, null=True, verbose_name="Content"
                    ),
                ),
                (
                    "content_uz",
                    models.TextField(
                        blank=True, db_index=True, null=True, verbose_name="Content"
                    ),
                ),
                (
                    "content_ru",
                    models.TextField(
                        blank=True, db_index=True, null=True, verbose_name="Content"
                    ),
                ),
                (
                    "content_en",
                    models.TextField(
                        blank=True, db_index=True, null=True, verbose_name="Content"
                    ),
                ),
                (
                    "content_ko",
                    models.TextField(
                        blank=True, db_index=True, null=True, verbose_name="Content"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        db_index=True,
                        help_text="Upload an image for the news article.",
                        null=True,
                        upload_to="news_images/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Number of times the article has been viewed.",
                        verbose_name="View Count",
                    ),
                ),
                (
                    "is_trending",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if the article is trending.",
                        verbose_name="Is Trending",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to="home.newscategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SeoMetaBlogData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "title_ko",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "description_uz",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "description_ko",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SEO Keywords",
                    ),
                ),
                (
                    "keywords_uz",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SEO Keywords",
                    ),
                ),
                (
                    "keywords_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SEO Keywords",
                    ),
                ),
                (
                    "keywords_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SEO Keywords",
                    ),
                ),
                (
                    "keywords_ko",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SEO Keywords",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Specify the canonical URL for SEO.",
                        null=True,
                        verbose_name="Canonical URL",
                    ),
                ),
                (
                    "blog",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo_meta",
                        to="home.blog",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Meta Data",
                "verbose_name_plural": "SEO Meta Data",
            },
        ),
        migrations.CreateModel(
            name="SeoMetaNewsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "title_ko",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "description_uz",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "description_ko",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SEO Keywords",
                    ),
                ),
                (
                    "keywords_uz",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SEO Keywords",
                    ),
                ),
                (
                    "keywords_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SEO Keywords",
                    ),
                ),
                (
                    "keywords_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SEO Keywords",
                    ),
                ),
                (
                    "keywords_ko",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SEO Keywords",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Specify the canonical URL for SEO.",
                        null=True,
                        verbose_name="Canonical URL",
                    ),
                ),
                (
                    "news",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo_meta",
                        to="home.news",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Meta Data",
                "verbose_name_plural": "SEO Meta Data",
            },
        ),
        migrations.CreateModel(
            name="SeoOgBlogData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="OG Title"
                    ),
                ),
                (
                    "og_title_uz",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="OG Title"
                    ),
                ),
                (
                    "og_title_ru",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="OG Title"
                    ),
                ),
                (
                    "og_title_en",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="OG Title"
                    ),
                ),
                (
                    "og_title_ko",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="OG Title"
                    ),
                ),
                (
                    "og_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="OG Description"
                    ),
                ),
                (
                    "og_description_uz",
                    models.TextField(
                        blank=True, null=True, verbose_name="OG Description"
                    ),
                ),
                (
                    "og_description_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="OG Description"
                    ),
                ),
                (
                    "og_description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="OG Description"
                    ),
                ),
                (
                    "og_description_ko",
                    models.TextField(
                        blank=True, null=True, verbose_name="OG Description"
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload an image for Open Graph.",
                        null=True,
                        upload_to="og_images/",
                        verbose_name="OG Image",
                    ),
                ),
                (
                    "blog",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="og_meta",
                        to="home.blog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Open Graph Meta Data",
                "verbose_name_plural": "Open Graph Meta Data",
            },
        ),
        migrations.CreateModel(
            name="SeoOgNewsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="OG Title"
                    ),
                ),
                (
                    "og_title_uz",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="OG Title"
                    ),
                ),
                (
                    "og_title_ru",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="OG Title"
                    ),
                ),
                (
                    "og_title_en",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="OG Title"
                    ),
                ),
                (
                    "og_title_ko",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="OG Title"
                    ),
                ),
                (
                    "og_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="OG Description"
                    ),
                ),
                (
                    "og_description_uz",
                    models.TextField(
                        blank=True, null=True, verbose_name="OG Description"
                    ),
                ),
                (
                    "og_description_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="OG Description"
                    ),
                ),
                (
                    "og_description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="OG Description"
                    ),
                ),
                (
                    "og_description_ko",
                    models.TextField(
                        blank=True, null=True, verbose_name="OG Description"
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload an image for Open Graph.",
                        null=True,
                        upload_to="og_images/",
                        verbose_name="OG Image",
                    ),
                ),
                (
                    "news",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="og_meta",
                        to="home.news",
                    ),
                ),
            ],
            options={
                "verbose_name": "Open Graph Meta Data",
                "verbose_name_plural": "Open Graph Meta Data",
            },
        ),
        migrations.CreateModel(
            name="SeoTwitterBlogData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "twitter_card",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Card",
                    ),
                ),
                (
                    "twitter_card_uz",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Card",
                    ),
                ),
                (
                    "twitter_card_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Card",
                    ),
                ),
                (
                    "twitter_card_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Card",
                    ),
                ),
                (
                    "twitter_card_ko",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Card",
                    ),
                ),
                (
                    "twitter_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_title_uz",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_title_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_title_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_title_ko",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Twitter Description"
                    ),
                ),
                (
                    "twitter_description_uz",
                    models.TextField(
                        blank=True, null=True, verbose_name="Twitter Description"
                    ),
                ),
                (
                    "twitter_description_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="Twitter Description"
                    ),
                ),
                (
                    "twitter_description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Twitter Description"
                    ),
                ),
                (
                    "twitter_description_ko",
                    models.TextField(
                        blank=True, null=True, verbose_name="Twitter Description"
                    ),
                ),
                (
                    "twitter_image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload an image for Twitter Card.",
                        null=True,
                        upload_to="twitter_images/",
                        verbose_name="Twitter Image",
                    ),
                ),
                (
                    "blog",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="twitter_meta",
                        to="home.blog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Twitter Card Meta Data",
                "verbose_name_plural": "Twitter Card Meta Data",
            },
        ),
        migrations.CreateModel(
            name="SeoTwitterNewsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "twitter_card",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Card",
                    ),
                ),
                (
                    "twitter_card_uz",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Card",
                    ),
                ),
                (
                    "twitter_card_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Card",
                    ),
                ),
                (
                    "twitter_card_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Card",
                    ),
                ),
                (
                    "twitter_card_ko",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Card",
                    ),
                ),
                (
                    "twitter_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_title_uz",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_title_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_title_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_title_ko",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Twitter Description"
                    ),
                ),
                (
                    "twitter_description_uz",
                    models.TextField(
                        blank=True, null=True, verbose_name="Twitter Description"
                    ),
                ),
                (
                    "twitter_description_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="Twitter Description"
                    ),
                ),
                (
                    "twitter_description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Twitter Description"
                    ),
                ),
                (
                    "twitter_description_ko",
                    models.TextField(
                        blank=True, null=True, verbose_name="Twitter Description"
                    ),
                ),
                (
                    "twitter_image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload an image for Twitter Card.",
                        null=True,
                        upload_to="twitter_images/",
                        verbose_name="Twitter Image",
                    ),
                ),
                (
                    "news",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="twitter_meta",
                        to="home.news",
                    ),
                ),
            ],
            options={
                "verbose_name": "Twitter Card Meta Data",
                "verbose_name_plural": "Twitter Card Meta Data",
            },
        ),
    ]
