# Generated by Django 5.1.5 on 2025-06-20 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0011_degree_name_en_degree_name_ko_degree_name_ru_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="document",
        ),
        migrations.RemoveField(
            model_name="user",
            name="response_file",
        ),
        migrations.RemoveField(
            model_name="user",
            name="status",
        ),
        migrations.RemoveField(
            model_name="user",
            name="status_file",
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "response_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="response_file/",
                        verbose_name="Javob hujjati",
                    ),
                ),
                (
                    "status_file",
                    models.CharField(
                        choices=[
                            ("NO_FILE", "Hujjat yuklanmagan"),
                            ("WAITING", "Hujjat topshirgan"),
                            ("ACCEPTED", "Shartnoma tuzilgan"),
                            ("REJECTED", "Shartnoma bekor qilingan"),
                        ],
                        default="NO_FILE",
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=False, verbose_name="Shartnoma statusi"
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=5,
                        default=0.0,
                        max_digits=100,
                        verbose_name="Balans",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Karta raqami",
                    ),
                ),
                (
                    "document",
                    models.ManyToManyField(
                        blank=True, to="pedagog.document", verbose_name="Hujjat"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foydalanuvchi profili",
                "verbose_name_plural": "Foydalanuvchi profillari",
                "ordering": ["-created_at"],
            },
        ),
    ]
