# Generated by Django 5.1.5 on 2025-08-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_document_remove_user_response_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bot", "Bot"),
                    ("mobile", "Mobile App"),
                    ("web", "Web"),
                    ("click_app", "Click App"),
                ],
                default="bot",
                max_length=100,
                null=True,
                verbose_name="Qayerdan ?",
            ),
        ),
    ]
