# Generated by Django 5.1.5 on 2025-08-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_referred_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_id",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Tg ID"),
        ),
    ]
