# Generated by Django 5.1.5 on 2025-08-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_tg_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
