# Generated by Django 5.1.5 on 2025-08-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_referral_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bot", "Bot"),
                    ("mobile", "Mobile App"),
                    ("web", "Web"),
                    ("click_app", "Click App"),
                ],
                default="web",
                max_length=100,
                null=True,
                verbose_name="Qayerdan ?",
            ),
        ),
    ]
