# Generated by Django 5.1.5 on 2025-08-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tg_id", models.BigIntegerField(verbose_name="Tg id")),
                ("first_name", models.CharField(max_length=100, verbose_name="Ism")),
            ],
            options={
                "verbose_name": "Bot Foydalanuvchilar",
                "verbose_name_plural": "Bot Foydalanuvchilar",
                "ordering": ["-created_at"],
            },
        ),
    ]
