# Generated by Django 5.1.5 on 2025-05-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "start_date",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Boshlanish sanasi"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tugash sanasi"
                    ),
                ),
                ("price", models.BigIntegerField(default=0, verbose_name="Narxi")),
                ("status", models.BooleanField(default=False, verbose_name="Holati")),
            ],
            options={
                "verbose_name": "Buyurtmalar",
                "verbose_name_plural": "Buyurtmalar",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.BigIntegerField(default=0, verbose_name="Narxi")),
                ("status", models.BooleanField(default=False, verbose_name="Holati")),
                (
                    "trans_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Tranzaksiya ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Payments",
                "verbose_name_plural": "Payments",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Plans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.BigIntegerField(default=0, verbose_name="Narxi")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name from Font Awesome",
                        max_length=255,
                        null=True,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Plan name",
                        max_length=255,
                        null=True,
                        verbose_name="Reja nomi",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the plan",
                        null=True,
                        verbose_name="Tavsif",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reja",
                "verbose_name_plural": "Rejalar",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PlansRequirements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Talab"
                    ),
                ),
            ],
            options={
                "verbose_name": "Reja talabi",
                "verbose_name_plural": "Reja talablar",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TransactionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Transaction ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("success", "success"),
                            ("error", "error"),
                        ],
                        default="pending",
                        max_length=100,
                        verbose_name="status",
                    ),
                ),
                (
                    "error",
                    models.TextField(blank=True, null=True, verbose_name="error"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Amount",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ("-create_at",),
            },
        ),
    ]
