# Generated by Django 5.1.5 on 2025-05-27 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payment", "0001_initial"),
        ("pedagog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="classes",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="pedagog.classes",
                verbose_name="Sinf",
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="science",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="pedagog.science",
                verbose_name="Fan",
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="science_language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="pedagog.sciencelanguage",
                verbose_name="Fan tili",
            ),
        ),
    ]
