# Generated by Django 5.1.5 on 2025-05-27 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payment", "0002_initial"),
        ("pedagog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Foydalanuvchi",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="payment.orders",
                verbose_name="Buyurtma",
            ),
        ),
        migrations.AddField(
            model_name="plans",
            name="quarter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pedagog.quarter",
                verbose_name="Chorak",
            ),
        ),
        migrations.AddField(
            model_name="plansrequirements",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="payment.plans",
                verbose_name="Reja",
            ),
        ),
        migrations.AddField(
            model_name="transactionmodel",
            name="moderator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pedagog.moderator",
                verbose_name="moderator",
            ),
        ),
    ]
