# Generated by Django 5.1.5 on 2025-06-04 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_initial"),
        ("pedagog", "0008_alter_media_topic_id_alter_media_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="quarter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="pedagog.quarter",
                verbose_name="Chorak",
            ),
            preserve_default=False,
        ),
    ]
