# Generated by Django 5.1.5 on 2025-08-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_orders_quarter"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="payment_type",
            field=models.CharField(
                choices=[("click", "Click"), ("payme", "Payme"), ("uzum", "Uzum")],
                default="click",
                max_length=10,
                verbose_name="To'lov turi",
            ),
        ),
    ]
