# Generated by Django 5.1.5 on 2025-08-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_orders_payment_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="payment_type",
        ),
    ]
