# Generated by Django 5.1.5 on 2025-08-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_remove_orders_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bot", "Bot"),
                    ("mobile", "Mobile App"),
                    ("web", "Web"),
                    ("click_app", "Click App"),
                ],
                default="bot",
                max_length=100,
                null=True,
                verbose_name="Qayerdan ?",
            ),
        ),
    ]
