# Generated by Django 5.1.5 on 2025-09-30 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0007_orders_source"),
        ("pedagog", "0025_electronresource_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="electronic_resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="pedagog.electronresource",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="classes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="pedagog.classes",
                verbose_name="Sinf",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="quarter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="pedagog.quarter",
                verbose_name="Chorak",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="science",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="pedagog.science",
                verbose_name="Fan",
            ),
        ),
    ]
