# Generated by Django 5.1.5 on 2025-05-27 12:52

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("ALL", "Barchasi"), ("TOPIC", "Mavzuga qarab")],
                        max_length=255,
                        verbose_name="Turi",
                    ),
                ),
                ("question", models.TextField(verbose_name="Savol")),
                ("answer", models.TextField(verbose_name="Javob")),
            ],
            options={
                "verbose_name": "Suniy Intellekt",
                "verbose_name_plural": "Suniy Intellektlar",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Classes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the class.",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the class.",
                        max_length=100,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the class.",
                        max_length=100,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the class.",
                        max_length=100,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_ko",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the class.",
                        max_length=100,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether the class is currently active.",
                        verbose_name="Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nomi"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Tasnifi"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/%Y/%m/%d/", verbose_name="Fayl"
                    ),
                ),
                (
                    "response_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/%Y/%m/%d/",
                        verbose_name="Javob fayli",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Holati")),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Turi"
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(
                        blank=True, default=0, null=True, verbose_name="Hajmi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hujjat",
                "verbose_name_plural": "Hujjatlar",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Download",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="Sanasi")),
                (
                    "object_type",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Yuklash turi",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Object ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Yuklamalar",
                "verbose_name_plural": "Yuklamalar",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DownloadToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Muddati")),
            ],
            options={
                "verbose_name": "Yuklash uchun token",
                "verbose_name_plural": "Yuklash uchun tokenlar",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ElectronResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="electron_resources/", verbose_name="File"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Size"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Type"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Electron Resource File",
                "verbose_name_plural": "Electron Resource Files",
                "db_table": "electron_resource_files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ElectronResourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "name_uz",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_ko",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_uz",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_ko",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "first_color",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="First Color",
                    ),
                ),
                (
                    "second_color",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Second Color",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Icon"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Electron Resource",
                "verbose_name_plural": "Electron Resources",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ElectronResourceSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "name_uz",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_ko",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_uz",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_ko",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Electron Resource Sub Category",
                "verbose_name_plural": "Electron Resource Sub Categories",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/images/",
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nomi"
                    ),
                ),
                (
                    "desc",
                    models.TextField(blank=True, null=True, verbose_name="Tavsif"),
                ),
                ("file", models.FileField(upload_to="media/", verbose_name="Fayl")),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Fayl turi"
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(
                        blank=True, default=0, null=True, verbose_name="Hajmi"
                    ),
                ),
                (
                    "count",
                    models.IntegerField(default=0, verbose_name="Yuklashlar soni"),
                ),
                (
                    "statistics",
                    models.CharField(
                        blank=True,
                        default="0%",
                        max_length=255,
                        null=True,
                        verbose_name="Statistika",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        blank=True,
                        default="plan",
                        max_length=255,
                        null=True,
                        verbose_name="Object turi",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Object turi ID"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Ko'rishlar soni"
                    ),
                ),
            ],
            options={
                "verbose_name": "Media",
                "verbose_name_plural": "Medialar",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Moderator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("balance", models.BigIntegerField(default=0, verbose_name="Balans")),
                (
                    "paid_amount",
                    models.BigIntegerField(default=0, verbose_name="To'langan pul"),
                ),
                (
                    "prosend",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        null=True,
                        verbose_name="Prosent",
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("HIGHER", "Oliy toifa"),
                            ("EXCELLENT", "Xalq ta'limi a'lochisi"),
                            (
                                "GOOD_TEACHER",
                                "\"Eng yaxshi o'qituvchi\" konkursi g'olibi",
                            ),
                            ("AUTHOR", "Darslik muallifi"),
                            ("POPULAR", "Ommlashtirilgan"),
                            ("METHODIST", "Metodist"),
                        ],
                        default="AUTHOR",
                        max_length=15,
                        verbose_name="Daraja",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Karta raqami",
                    ),
                ),
                (
                    "is_contracted",
                    models.BooleanField(default=False, verbose_name="Tasdiqlash"),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=False, verbose_name="Shartnoma statusi"
                    ),
                ),
                (
                    "plan_creatable",
                    models.BooleanField(
                        default=False, verbose_name="Tematik Reja yarata olishi"
                    ),
                ),
                (
                    "resource_creatable",
                    models.BooleanField(
                        default=False, verbose_name="Resurs yarata olishi."
                    ),
                ),
                (
                    "topic_creatable",
                    models.BooleanField(
                        default=False, verbose_name="Mavzu yarata olishi."
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderator",
                "verbose_name_plural": "Moderatorlar",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "hour",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Soat"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tematik reja",
                "verbose_name_plural": "Tematik rejalar",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Quarter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nomi")),
                (
                    "choices",
                    models.IntegerField(
                        choices=[
                            (1, "First Quarter"),
                            (2, "Second Quarter"),
                            (3, "Third Quarter"),
                            (4, "Fourth Quarter"),
                        ],
                        default=1,
                        verbose_name="Chorak",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        default=datetime.datetime.today,
                        verbose_name="Boshlang'ich sana",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        default=datetime.datetime.today,
                        verbose_name="Oxirgi sana",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chorak",
                "verbose_name_plural": "Choraklar",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SchoolType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the school type.",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the school type.",
                        max_length=100,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the school type.",
                        max_length=100,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the school type.",
                        max_length=100,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_ko",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the school type.",
                        max_length=100,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether the school type is currently active.",
                        verbose_name="Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "School Type",
                "verbose_name_plural": "School Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Science",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the science subject.",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the science subject.",
                        max_length=100,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the science subject.",
                        max_length=100,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the science subject.",
                        max_length=100,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_ko",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the science subject.",
                        max_length=100,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether the science is currently active.",
                        verbose_name="Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Science",
                "verbose_name_plural": "Sciences",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScienceLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the science language.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the science language.",
                        max_length=255,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the science language.",
                        max_length=255,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the science language.",
                        max_length=255,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_ko",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the science language.",
                        max_length=255,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether the science language is currently active.",
                        verbose_name="Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Science Language",
                "verbose_name_plural": "Science Languages",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SeoMetaCategoryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "title_ko",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "description_uz",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "description_ko",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SEO Keywords",
                    ),
                ),
                (
                    "keywords_uz",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SEO Keywords",
                    ),
                ),
                (
                    "keywords_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SEO Keywords",
                    ),
                ),
                (
                    "keywords_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SEO Keywords",
                    ),
                ),
                (
                    "keywords_ko",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SEO Keywords",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Specify the canonical URL for SEO.",
                        null=True,
                        verbose_name="Canonical URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Meta Data",
                "verbose_name_plural": "SEO Meta Data",
            },
        ),
        migrations.CreateModel(
            name="SeoOgCategoryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="OG Title"
                    ),
                ),
                (
                    "og_title_uz",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="OG Title"
                    ),
                ),
                (
                    "og_title_ru",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="OG Title"
                    ),
                ),
                (
                    "og_title_en",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="OG Title"
                    ),
                ),
                (
                    "og_title_ko",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="OG Title"
                    ),
                ),
                (
                    "og_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="OG Description"
                    ),
                ),
                (
                    "og_description_uz",
                    models.TextField(
                        blank=True, null=True, verbose_name="OG Description"
                    ),
                ),
                (
                    "og_description_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="OG Description"
                    ),
                ),
                (
                    "og_description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="OG Description"
                    ),
                ),
                (
                    "og_description_ko",
                    models.TextField(
                        blank=True, null=True, verbose_name="OG Description"
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload an image for Open Graph.",
                        null=True,
                        upload_to="og_images/",
                        verbose_name="OG Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Open Graph Meta Data",
                "verbose_name_plural": "Open Graph Meta Data",
            },
        ),
        migrations.CreateModel(
            name="SeoTwitterCategoryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "twitter_card",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Card",
                    ),
                ),
                (
                    "twitter_card_uz",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Card",
                    ),
                ),
                (
                    "twitter_card_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Card",
                    ),
                ),
                (
                    "twitter_card_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Card",
                    ),
                ),
                (
                    "twitter_card_ko",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Card",
                    ),
                ),
                (
                    "twitter_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_title_uz",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_title_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_title_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_title_ko",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Twitter Description"
                    ),
                ),
                (
                    "twitter_description_uz",
                    models.TextField(
                        blank=True, null=True, verbose_name="Twitter Description"
                    ),
                ),
                (
                    "twitter_description_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="Twitter Description"
                    ),
                ),
                (
                    "twitter_description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Twitter Description"
                    ),
                ),
                (
                    "twitter_description_ko",
                    models.TextField(
                        blank=True, null=True, verbose_name="Twitter Description"
                    ),
                ),
                (
                    "twitter_image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload an image for Twitter Card.",
                        null=True,
                        upload_to="twitter_images/",
                        verbose_name="Twitter Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Twitter Card Meta Data",
                "verbose_name_plural": "Twitter Card Meta Data",
            },
        ),
        migrations.CreateModel(
            name="TMRAppeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("accepted", "Qabul qilindi"),
                            ("rejected", "Rad etildi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
            ],
            options={
                "verbose_name": "TMR arizalari",
                "verbose_name_plural": "TMR arizalari",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TmrFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nomi"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Tasnifi"),
                ),
                (
                    "file",
                    models.FileField(upload_to="tmr/%Y/%m/%d/", verbose_name="Fayl"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Holati")),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Turi"
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(
                        blank=True, default=0, null=True, verbose_name="Hajmi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tmr Fayllari",
                "verbose_name_plural": "Tmr Fayllari",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nomi")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Tavsif"),
                ),
                (
                    "sequence_number",
                    models.IntegerField(default=1, verbose_name="Mavzu raqami"),
                ),
                (
                    "hours",
                    models.PositiveIntegerField(default=0, verbose_name="Soatlar"),
                ),
                (
                    "weeks",
                    models.PositiveIntegerField(
                        blank=True, default=1, null=True, verbose_name="Haftalar"
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="topic/banner/",
                        verbose_name="Banner",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Ko'rishlar soni"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mavzu",
                "verbose_name_plural": "Mavzular",
                "ordering": ["sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="Weeks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("week_count", models.IntegerField(verbose_name="Hafta raqami")),
                (
                    "start_date",
                    models.DateField(verbose_name="Haftaning boshlanish sanasi"),
                ),
                ("end_date", models.DateField(verbose_name="Haftaning tugash sanasi")),
            ],
            options={
                "verbose_name": "Hafta",
                "verbose_name_plural": "Haftalar",
                "ordering": ("-created_at",),
            },
        ),
    ]
