# Generated by Django 5.1.5 on 2025-06-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0003_lessonschedule"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Weeks",
        ),
    ]
