# Generated by Django 5.1.5 on 2025-06-03 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0004_delete_weeks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Degree Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Degree",
                "verbose_name_plural": "Degrees",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="moderator",
            name="degree",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderators",
                to="pedagog.degree",
                verbose_name="Daraja",
            ),
        ),
    ]
