# Generated by Django 5.1.5 on 2025-06-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0005_degree_alter_moderator_degree"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the class group.",
                        max_length=20,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the class group.",
                        max_length=20,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the class group.",
                        max_length=20,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the class group.",
                        max_length=20,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_ko",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the class group.",
                        max_length=20,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Group",
                "verbose_name_plural": "Class Groups",
                "ordering": ["name"],
            },
        ),
    ]
