# Generated by Django 5.1.5 on 2025-06-04 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0006_classgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonschedule",
            name="class_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule",
                to="pedagog.classgroup",
                verbose_name="Sinf guruhi",
            ),
        ),
    ]
