# Generated by Django 5.1.5 on 2025-06-04 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0007_lessonschedule_class_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="topic_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medias",
                to="pedagog.topic",
                verbose_name="Mavzu",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="media",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Foydalanuvchi",
            ),
            preserve_default=False,
        ),
    ]
