# Generated by Django 5.1.5 on 2025-06-09 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0008_alter_media_topic_id_alter_media_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lessonschedule",
            name="unique_schedule_per_class_date_time",
        ),
        migrations.AddConstraint(
            model_name="lessonschedule",
            constraint=models.UniqueConstraint(
                fields=("classes", "date", "start_time", "shift"),
                name="unique_schedule_per_class_date_time",
            ),
        ),
    ]
