# Generated by Django 5.1.5 on 2025-06-11 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pedagog",
            "0009_remove_lessonschedule_unique_schedule_per_class_date_time_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lessonschedule",
            options={"ordering": ["weekday", "lesson_number", "start_time"]},
        ),
        migrations.RemoveConstraint(
            model_name="lessonschedule",
            name="unique_schedule_per_class_date_time",
        ),
        migrations.RemoveField(
            model_name="lessonschedule",
            name="date",
        ),
        migrations.RemoveField(
            model_name="lessonschedule",
            name="topic",
        ),
        migrations.AddField(
            model_name="lessonschedule",
            name="color",
            field=models.CharField(
                default="#FFFFFF",
                help_text="Color in hex format, e.g., #FF5733",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="lessonschedule",
            name="schedule_type",
            field=models.CharField(
                choices=[
                    ("FIRST_WEEK", "Birinchi hafta"),
                    ("SECOND_WEEK", "Ikkinchi hafta"),
                ],
                default="FIRST_WEEK",
                help_text="Reja turi: Birinchi hafta yoki Ikkinchi hafta",
                max_length=20,
                verbose_name="Reja turi",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonschedule",
            constraint=models.UniqueConstraint(
                fields=(
                    "classes",
                    "weekday",
                    "shift",
                    "science",
                    "lesson_number",
                    "start_time",
                    "end_time",
                ),
                name="unique_schedule_per_class_date_time",
            ),
        ),
    ]
