# Generated by Django 5.1.5 on 2025-06-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0010_alter_lessonschedule_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="degree",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Degree Name"
            ),
        ),
        migrations.AddField(
            model_name="degree",
            name="name_ko",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Degree Name"
            ),
        ),
        migrations.AddField(
            model_name="degree",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Degree Name"
            ),
        ),
        migrations.AddField(
            model_name="degree",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Degree Name"
            ),
        ),
    ]
