# Generated by Django 5.1.5 on 2025-07-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0013_bannermodel_alter_download_media"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name="title")),
                ("logo", models.ImageField(upload_to="", verbose_name="image")),
                ("url", models.URLField(verbose_name="url")),
            ],
        ),
    ]
