# Generated by Django 5.1.5 on 2025-07-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0014_servicesmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("desc", models.TextField(verbose_name="Desc")),
                ("duration", models.PositiveIntegerField(verbose_name="Duration")),
                ("video", models.URLField(verbose_name="Video link")),
                (
                    "badge_title",
                    models.CharField(max_length=255, verbose_name="badge title"),
                ),
                (
                    "badge_color",
                    models.CharField(max_length=255, verbose_name="badge color"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="servicesmodel",
            name="logo",
        ),
        migrations.AddField(
            model_name="bannermodel",
            name="button_link",
            field=models.URLField(default=1, max_length=255, verbose_name="button url"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bannermodel",
            name="button_title",
            field=models.CharField(
                default=1, max_length=255, verbose_name="button title"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="document_file",
            field=models.FileField(
                default=1, upload_to="documents/", verbose_name="Document file"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="passport_file",
            field=models.FileField(
                default=1, upload_to="passports/", verbose_name="Passport file"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicesmodel",
            name="desc",
            field=models.TextField(default=1, verbose_name="descirption"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicesmodel",
            name="icon",
            field=models.CharField(default=1, max_length=255, verbose_name="icon"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicesmodel",
            name="icon_color",
            field=models.CharField(
                default=1, max_length=100, verbose_name="icon color"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="servicesmodel",
            name="url",
            field=models.CharField(max_length=1000, verbose_name="url"),
        ),
    ]
