# Generated by Django 5.1.5 on 2025-07-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0015_videomodel_remove_servicesmodel_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bannermodel",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="bannermodel",
            name="description_ko",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="bannermodel",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="bannermodel",
            name="description_uz",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="bannermodel",
            name="title_en",
            field=models.CharField(null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="bannermodel",
            name="title_ko",
            field=models.CharField(null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="bannermodel",
            name="title_ru",
            field=models.CharField(null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="bannermodel",
            name="title_uz",
            field=models.CharField(null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="servicesmodel",
            name="desc_en",
            field=models.TextField(null=True, verbose_name="descirption"),
        ),
        migrations.AddField(
            model_name="servicesmodel",
            name="desc_ko",
            field=models.TextField(null=True, verbose_name="descirption"),
        ),
        migrations.AddField(
            model_name="servicesmodel",
            name="desc_ru",
            field=models.TextField(null=True, verbose_name="descirption"),
        ),
        migrations.AddField(
            model_name="servicesmodel",
            name="desc_uz",
            field=models.TextField(null=True, verbose_name="descirption"),
        ),
        migrations.AddField(
            model_name="servicesmodel",
            name="title_en",
            field=models.CharField(null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="servicesmodel",
            name="title_ko",
            field=models.CharField(null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="servicesmodel",
            name="title_ru",
            field=models.CharField(null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="servicesmodel",
            name="title_uz",
            field=models.CharField(null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="videomodel",
            name="desc_en",
            field=models.TextField(null=True, verbose_name="Desc"),
        ),
        migrations.AddField(
            model_name="videomodel",
            name="desc_ko",
            field=models.TextField(null=True, verbose_name="Desc"),
        ),
        migrations.AddField(
            model_name="videomodel",
            name="desc_ru",
            field=models.TextField(null=True, verbose_name="Desc"),
        ),
        migrations.AddField(
            model_name="videomodel",
            name="desc_uz",
            field=models.TextField(null=True, verbose_name="Desc"),
        ),
        migrations.AddField(
            model_name="videomodel",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="videomodel",
            name="title_ko",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="videomodel",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="videomodel",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
    ]
