# Generated by Django 5.1.5 on 2025-07-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0016_bannermodel_description_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="files/", verbose_name="file")),
            ],
        ),
        migrations.RemoveField(
            model_name="document",
            name="document_file",
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents/%Y/%m/%d/",
                verbose_name="Fayl",
            ),
        ),
        migrations.RemoveField(
            model_name="document",
            name="passport_file",
        ),
        migrations.AddField(
            model_name="document",
            name="document_file",
            field=models.ManyToManyField(
                related_name="ddocyment", to="pedagog.filemodel"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="passport_file",
            field=models.ManyToManyField(
                related_name="pdocument", to="pedagog.filemodel"
            ),
        ),
    ]
