# Generated by Django 5.1.5 on 2025-07-23 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0017_filemodel_remove_document_document_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConvertedMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="converted_images/")),
                ("page_number", models.PositiveIntegerField()),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="converted_medias",
                        to="pedagog.media",
                    ),
                ),
            ],
            options={
                "verbose_name": "O'zgartirilgan media",
                "verbose_name_plural": "O'zgartirilgan media",
                "ordering": ("-created_at",),
            },
        ),
    ]
