# Generated by Django 5.1.5 on 2025-07-25 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0018_convertedmedia"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "media types",
                "ordering": ("created_at",),
            },
        ),
        migrations.AlterModelOptions(
            name="convertedmedia",
            options={
                "ordering": ("-created_at", "page_number"),
                "verbose_name": "O'zgartirilgan media",
                "verbose_name_plural": "O'zgartirilgan media",
            },
        ),
        migrations.AddField(
            model_name="media",
            name="media_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pedagog.mediatype",
                verbose_name="Resurs turi",
            ),
        ),
    ]
