# Generated by Django 5.1.5 on 2025-07-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0019_mediatype_alter_convertedmedia_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediatype",
            name="name_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mediatype",
            name="name_ko",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mediatype",
            name="name_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mediatype",
            name="name_uz",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
