# Generated by Django 5.1.5 on 2025-07-29 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0020_mediatype_name_en_mediatype_name_ko_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classes",
            options={
                "ordering": ["id"],
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
            },
        ),
    ]
