# Generated by Django 5.1.5 on 2025-08-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0021_alter_classes_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="convertedmedia",
            options={
                "ordering": ("page_number",),
                "verbose_name": "O'zgartirilgan media",
                "verbose_name_plural": "O'zgartirilgan media",
            },
        ),
    ]
