# Generated by Django 5.1.5 on 2025-09-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0022_alter_convertedmedia_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Link"),
        ),
    ]
