# Generated by Django 5.1.5 on 2025-09-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0023_media_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="preview",
            field=models.FileField(blank=True, null=True, upload_to="media/"),
        ),
    ]
