# Generated by Django 5.1.5 on 2025-09-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0024_media_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="electronresource",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
