# Generated by Django 5.1.5 on 2025-10-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0025_electronresource_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="electronresource",
            name="preview",
            field=models.FileField(
                blank=True, null=True, upload_to="electron_resources/"
            ),
        ),
    ]
