# Generated by Django 5.1.5 on 2025-10-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0026_electronresource_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bannermodel",
            name="button_link",
            field=models.CharField(max_length=255, verbose_name="button url"),
        ),
    ]
