# Generated by Django 5.1.5 on 2025-11-12 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0027_alter_bannermodel_button_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chat_id", models.BigIntegerField(verbose_name="Telegram Chat ID")),
                (
                    "message_id",
                    models.BigIntegerField(verbose_name="Telegram Message ID"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Yuborilgan vaqti",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
