# Generated by Django 5.1.5 on 2025-11-12 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagog", "0028_telegrammessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegrammessage",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="telegrammessage",
            name="media",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="pedagog.media",
            ),
            preserve_default=False,
        ),
    ]
